# RocketMQ Broker 配置
brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH

# 明确指定 store 路径（在 compose 中已挂载到 /home/rocketmq/store）
storePathRootDir = /home/rocketmq/store
storePathCommitLog = /home/rocketmq/store/commitlog

# Docker 环境中的 Broker IP 配置
# 使用容器名，让其他容器能够访问
brokerIP1 = broker

# 自动创建 Topic
autoCreateTopicEnable = true
autoCreateSubscriptionGroup = true
